package com.etologic.mahjongtournamentsuite.domain.model

data class TableState(
    val roundId: Int,
    val tableId: Int,
    val playerIds: List<Int>,
    val playerEastId: String,
    val playerSouthId: String,
    val playerWestId: String,
    val playerNorthId: String,
    val playerEastScore: String,
    val playerSouthScore: String,
    val playerWestScore: String,
    val playerNorthScore: String,
    val playerEastPoints: String,
    val playerSouthPoints: String,
    val playerWestPoints: String,
    val playerNorthPoints: String,
    val manualPlayerEastScore: String = "",
    val manualPlayerSouthScore: String = "",
    val manualPlayerWestScore: String = "",
    val manualPlayerNorthScore: String = "",
    val manualPlayerEastPoints: String = "",
    val manualPlayerSouthPoints: String = "",
    val manualPlayerWestPoints: String = "",
    val manualPlayerNorthPoints: String = "",
    val isCompleted: Boolean,
    val useTotalsOnly: Boolean,
    val usePointsCalculation: Boolean,
)

data class TableHand(
    val handId: Int,
    val playerWinnerId: String,
    val playerLooserId: String,
    val handScore: String,
    val isChickenHand: Boolean,
    val playerEastPenalty: String,
    val playerSouthPenalty: String,
    val playerWestPenalty: String,
    val playerNorthPenalty: String,
)
