#!/usr/bin/env bash
# Downloads the pinned Flag Icons 4:3 SVG set and regenerates CountryFlagResources.kt.
# Source: https://github.com/lipis/flag-icons (MIT License, see LICENSE.flag-icons).
set -euo pipefail

readonly script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly project_dir="$(cd "$script_dir/.." && pwd)"
readonly version="v7.5.0"
readonly archive_url="https://github.com/lipis/flag-icons/archive/refs/tags/$version.zip"
readonly flags_dir="$project_dir/composeApp/src/commonMain/composeResources/drawable"
readonly source_file="$project_dir/composeApp/src/commonMain/kotlin/com/etologic/mahjongtournamentsuite/presentation/components/CountryFlagResources.kt"
readonly license_file="$project_dir/third_party/flag-icons/LICENSE"
readonly codes=(
  AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BJ BL BM BN BO BQ BR BS BT BV BW BY BZ
  CA CC CD CF CG CH CI CK CL CM CN CO CR CU CV CW CX CY CZ DE DJ DK DM DO DZ EC EE EG EH ER ES ET EU FI FJ FK FM FO
  FR GA GB GD GE GF GG GH GI GL GM GN GP GQ GR GS GT GU GW GY HK HM HN HR HT HU ID IE IL IM IN IO IQ IR IS IT JE JM
  JO JP KE KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MF MG MH MK ML MM MN MO MP MQ
  MR MS MT MU MV MW MX MY MZ NA NC NE NF NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PM PN PR PS PT PW PY QA RE
  RO RS RU RW SA SB SC SD SE SG SH SI SJ SK SL SM SN SO SR SS ST SV SX SY SZ TC TD TF TG TH TJ TK TL TM TN TO TR TT
  TV TW TZ UA UG UM US UY UZ VA VC VE VG VI VN VU WF WS XK YE YT ZA ZM ZW
)

lowercase() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]'
}

tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT
curl --fail --location --silent --show-error "$archive_url" --output "$tmp_dir/flag-icons.zip"
mkdir -p "$flags_dir"
rm -f "$flags_dir"/flag_??.svg
for code in "${codes[@]}"; do
  lowercase_code="$(lowercase "$code")"
  flag_file="$flags_dir/flag_$lowercase_code.svg"
  unzip -p "$tmp_dir/flag-icons.zip" "flag-icons-${version#v}/flags/4x3/$lowercase_code.svg" > "$flag_file"
  if ! rg -q 'viewBox="0 0 640 480"' "$flag_file"; then
    echo "Flag $code does not have the required 4:3 viewBox." >&2
    exit 1
  fi
done
mkdir -p "$(dirname "$license_file")"
unzip -p "$tmp_dir/flag-icons.zip" "flag-icons-${version#v}/LICENSE" > "$license_file"

{
  echo '// Generated by scripts/download-country-flags.sh. Do not edit by hand.'
  echo 'package com.etologic.mahjongtournamentsuite.presentation.components'
  echo
  echo 'import org.jetbrains.compose.resources.DrawableResource'
  echo 'import mahjongtournamentsuite.composeapp.generated.resources.Res'
  for code in "${codes[@]}"; do
    echo "import mahjongtournamentsuite.composeapp.generated.resources.flag_$(lowercase "$code")"
  done
  echo
  echo 'internal fun flagResourceFor(code: String): DrawableResource? = when (code) {'
  for code in "${codes[@]}"; do
    echo "    \"$code\" -> Res.drawable.flag_$(lowercase "$code")"
  done
  echo '    else -> null'
  echo '}'
} > "$source_file"

echo "Downloaded ${#codes[@]} normalized 4:3 flag SVG files."
