#!/usr/bin/env bash
# Downloads the pinned Twemoji SVG files for country flags, chicken, trophy and status icons.
# It also regenerates CountryFlagResources.kt.
# Source: https://github.com/jdecked/twemoji (CC-BY 4.0, see third_party/twemoji).
set -euo pipefail

readonly script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly project_dir="$(cd "$script_dir/.." && pwd)"
readonly version="v15.1.0"
readonly base_url="https://raw.githubusercontent.com/jdecked/twemoji/$version"
readonly flags_dir="$project_dir/composeApp/src/commonMain/composeResources/drawable"
readonly source_file="$project_dir/composeApp/src/commonMain/kotlin/com/etologic/mahjongtournamentsuite/presentation/components/CountryFlagResources.kt"
readonly license_file="$project_dir/third_party/twemoji/LICENSE-GRAPHICS"
readonly codes=(
  AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BJ BL BM BN BO BQ BR BS BT BV BW BY BZ
  CA CC CD CF CG CH CI CK CL CM CN CO CR CU CV CW CX CY CZ DE DJ DK DM DO DZ EC EE EG EH ER ES ET EU FI FJ FK FM FO
  FR GA GB GD GE GF GG GH GI GL GM GN GP GQ GR GS GT GU GW GY HK HM HN HR HT HU ID IE IL IM IN IO IQ IR IS IT JE JM
  JO JP KE KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MF MG MH MK ML MM MN MO MP MQ
  MR MS MT MU MV MW MX MY MZ NA NC NE NF NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PM PN PR PS PT PW PY QA RE
  RO RS RU RW SA SB SC SD SE SG SH SI SJ SK SL SM SN SO SR SS ST SV SX SY SZ TC TD TF TG TH TJ TK TL TM TN TO TR TT
  TV TW TZ UA UG UM US UY UZ VA VC VE VG VI VN VU WF WS XK YE YT ZA ZM ZW
)

lowercase() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]'
}

# Regional indicator code points: A is U+1F1E6.
flag_codepoints() {
  local letters="$1" result="" i char
  for ((i = 0; i < ${#letters}; i++)); do
    char="${letters:i:1}"
    result+="$(printf '%x' $((0x1F1E6 + $(printf '%d' "'$char") - 97)))-"
  done
  printf '%s' "${result%-}"
}

download() {
  curl --fail --location --silent --show-error "$base_url/assets/svg/$1.svg" --output "$2"
}

# Download first into a temporary folder, so a failure does not leave the app without flags.
tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT
for code in "${codes[@]}"; do
  lowercase_code="$(lowercase "$code")"
  download "$(flag_codepoints "$lowercase_code")" "$tmp_dir/flag_$lowercase_code.svg"
done
# name:codepoint
for icon in icon_chicken:1f414 icon_trophy:1f3c6 icon_status_empty:26aa icon_status_in_progress:23f3 \
  icon_status_manual:2611 icon_status_completed:2705; do
  download "${icon#*:}" "$tmp_dir/${icon%%:*}.svg"
done
mkdir -p "$(dirname "$license_file")"
curl --fail --location --silent --show-error "$base_url/LICENSE-GRAPHICS" --output "$license_file"

mkdir -p "$flags_dir"
rm -f "$flags_dir"/flag_??.svg
cp "$tmp_dir"/*.svg "$flags_dir"/

{
  echo '// Generated by scripts/download-country-flags.sh. Do not edit by hand.'
  echo 'package com.etologic.mahjongtournamentsuite.presentation.components'
  echo
  echo 'import org.jetbrains.compose.resources.DrawableResource'
  echo 'import mahjongtournamentsuite.composeapp.generated.resources.Res'
  for code in "${codes[@]}"; do
    echo "import mahjongtournamentsuite.composeapp.generated.resources.flag_$(lowercase "$code")"
  done
  echo
  echo 'internal fun flagResourceFor(code: String): DrawableResource? = when (code) {'
  for code in "${codes[@]}"; do
    echo "    \"$code\" -> Res.drawable.flag_$(lowercase "$code")"
  done
  echo '    else -> null'
  echo '}'
} > "$source_file"

echo "Downloaded ${#codes[@]} flag SVG files and 6 icon SVG files."
