// Generated by scripts/download-country-flags.sh. Do not edit by hand.
package com.etologic.mahjongtournamentsuite.presentation.components

import org.jetbrains.compose.resources.DrawableResource
import mahjongtournamentsuite.composeapp.generated.resources.Res
import mahjongtournamentsuite.composeapp.generated.resources.flag_ad
import mahjongtournamentsuite.composeapp.generated.resources.flag_ae
import mahjongtournamentsuite.composeapp.generated.resources.flag_af
import mahjongtournamentsuite.composeapp.generated.resources.flag_ag
import mahjongtournamentsuite.composeapp.generated.resources.flag_ai
import mahjongtournamentsuite.composeapp.generated.resources.flag_al
import mahjongtournamentsuite.composeapp.generated.resources.flag_am
import mahjongtournamentsuite.composeapp.generated.resources.flag_ao
import mahjongtournamentsuite.composeapp.generated.resources.flag_aq
import mahjongtournamentsuite.composeapp.generated.resources.flag_ar
import mahjongtournamentsuite.composeapp.generated.resources.flag_as
import mahjongtournamentsuite.composeapp.generated.resources.flag_at
import mahjongtournamentsuite.composeapp.generated.resources.flag_au
import mahjongtournamentsuite.composeapp.generated.resources.flag_aw
import mahjongtournamentsuite.composeapp.generated.resources.flag_ax
import mahjongtournamentsuite.composeapp.generated.resources.flag_az
import mahjongtournamentsuite.composeapp.generated.resources.flag_ba
import mahjongtournamentsuite.composeapp.generated.resources.flag_bb
import mahjongtournamentsuite.composeapp.generated.resources.flag_bd
import mahjongtournamentsuite.composeapp.generated.resources.flag_be
import mahjongtournamentsuite.composeapp.generated.resources.flag_bf
import mahjongtournamentsuite.composeapp.generated.resources.flag_bg
import mahjongtournamentsuite.composeapp.generated.resources.flag_bh
import mahjongtournamentsuite.composeapp.generated.resources.flag_bi
import mahjongtournamentsuite.composeapp.generated.resources.flag_bj
import mahjongtournamentsuite.composeapp.generated.resources.flag_bl
import mahjongtournamentsuite.composeapp.generated.resources.flag_bm
import mahjongtournamentsuite.composeapp.generated.resources.flag_bn
import mahjongtournamentsuite.composeapp.generated.resources.flag_bo
import mahjongtournamentsuite.composeapp.generated.resources.flag_bq
import mahjongtournamentsuite.composeapp.generated.resources.flag_br
import mahjongtournamentsuite.composeapp.generated.resources.flag_bs
import mahjongtournamentsuite.composeapp.generated.resources.flag_bt
import mahjongtournamentsuite.composeapp.generated.resources.flag_bv
import mahjongtournamentsuite.composeapp.generated.resources.flag_bw
import mahjongtournamentsuite.composeapp.generated.resources.flag_by
import mahjongtournamentsuite.composeapp.generated.resources.flag_bz
import mahjongtournamentsuite.composeapp.generated.resources.flag_ca
import mahjongtournamentsuite.composeapp.generated.resources.flag_cc
import mahjongtournamentsuite.composeapp.generated.resources.flag_cd
import mahjongtournamentsuite.composeapp.generated.resources.flag_cf
import mahjongtournamentsuite.composeapp.generated.resources.flag_cg
import mahjongtournamentsuite.composeapp.generated.resources.flag_ch
import mahjongtournamentsuite.composeapp.generated.resources.flag_ci
import mahjongtournamentsuite.composeapp.generated.resources.flag_ck
import mahjongtournamentsuite.composeapp.generated.resources.flag_cl
import mahjongtournamentsuite.composeapp.generated.resources.flag_cm
import mahjongtournamentsuite.composeapp.generated.resources.flag_cn
import mahjongtournamentsuite.composeapp.generated.resources.flag_co
import mahjongtournamentsuite.composeapp.generated.resources.flag_cr
import mahjongtournamentsuite.composeapp.generated.resources.flag_cu
import mahjongtournamentsuite.composeapp.generated.resources.flag_cv
import mahjongtournamentsuite.composeapp.generated.resources.flag_cw
import mahjongtournamentsuite.composeapp.generated.resources.flag_cx
import mahjongtournamentsuite.composeapp.generated.resources.flag_cy
import mahjongtournamentsuite.composeapp.generated.resources.flag_cz
import mahjongtournamentsuite.composeapp.generated.resources.flag_de
import mahjongtournamentsuite.composeapp.generated.resources.flag_dj
import mahjongtournamentsuite.composeapp.generated.resources.flag_dk
import mahjongtournamentsuite.composeapp.generated.resources.flag_dm
import mahjongtournamentsuite.composeapp.generated.resources.flag_do
import mahjongtournamentsuite.composeapp.generated.resources.flag_dz
import mahjongtournamentsuite.composeapp.generated.resources.flag_ec
import mahjongtournamentsuite.composeapp.generated.resources.flag_ee
import mahjongtournamentsuite.composeapp.generated.resources.flag_eg
import mahjongtournamentsuite.composeapp.generated.resources.flag_eh
import mahjongtournamentsuite.composeapp.generated.resources.flag_er
import mahjongtournamentsuite.composeapp.generated.resources.flag_es
import mahjongtournamentsuite.composeapp.generated.resources.flag_et
import mahjongtournamentsuite.composeapp.generated.resources.flag_eu
import mahjongtournamentsuite.composeapp.generated.resources.flag_fi
import mahjongtournamentsuite.composeapp.generated.resources.flag_fj
import mahjongtournamentsuite.composeapp.generated.resources.flag_fk
import mahjongtournamentsuite.composeapp.generated.resources.flag_fm
import mahjongtournamentsuite.composeapp.generated.resources.flag_fo
import mahjongtournamentsuite.composeapp.generated.resources.flag_fr
import mahjongtournamentsuite.composeapp.generated.resources.flag_ga
import mahjongtournamentsuite.composeapp.generated.resources.flag_gb
import mahjongtournamentsuite.composeapp.generated.resources.flag_gd
import mahjongtournamentsuite.composeapp.generated.resources.flag_ge
import mahjongtournamentsuite.composeapp.generated.resources.flag_gf
import mahjongtournamentsuite.composeapp.generated.resources.flag_gg
import mahjongtournamentsuite.composeapp.generated.resources.flag_gh
import mahjongtournamentsuite.composeapp.generated.resources.flag_gi
import mahjongtournamentsuite.composeapp.generated.resources.flag_gl
import mahjongtournamentsuite.composeapp.generated.resources.flag_gm
import mahjongtournamentsuite.composeapp.generated.resources.flag_gn
import mahjongtournamentsuite.composeapp.generated.resources.flag_gp
import mahjongtournamentsuite.composeapp.generated.resources.flag_gq
import mahjongtournamentsuite.composeapp.generated.resources.flag_gr
import mahjongtournamentsuite.composeapp.generated.resources.flag_gs
import mahjongtournamentsuite.composeapp.generated.resources.flag_gt
import mahjongtournamentsuite.composeapp.generated.resources.flag_gu
import mahjongtournamentsuite.composeapp.generated.resources.flag_gw
import mahjongtournamentsuite.composeapp.generated.resources.flag_gy
import mahjongtournamentsuite.composeapp.generated.resources.flag_hk
import mahjongtournamentsuite.composeapp.generated.resources.flag_hm
import mahjongtournamentsuite.composeapp.generated.resources.flag_hn
import mahjongtournamentsuite.composeapp.generated.resources.flag_hr
import mahjongtournamentsuite.composeapp.generated.resources.flag_ht
import mahjongtournamentsuite.composeapp.generated.resources.flag_hu
import mahjongtournamentsuite.composeapp.generated.resources.flag_id
import mahjongtournamentsuite.composeapp.generated.resources.flag_ie
import mahjongtournamentsuite.composeapp.generated.resources.flag_il
import mahjongtournamentsuite.composeapp.generated.resources.flag_im
import mahjongtournamentsuite.composeapp.generated.resources.flag_in
import mahjongtournamentsuite.composeapp.generated.resources.flag_io
import mahjongtournamentsuite.composeapp.generated.resources.flag_iq
import mahjongtournamentsuite.composeapp.generated.resources.flag_ir
import mahjongtournamentsuite.composeapp.generated.resources.flag_is
import mahjongtournamentsuite.composeapp.generated.resources.flag_it
import mahjongtournamentsuite.composeapp.generated.resources.flag_je
import mahjongtournamentsuite.composeapp.generated.resources.flag_jm
import mahjongtournamentsuite.composeapp.generated.resources.flag_jo
import mahjongtournamentsuite.composeapp.generated.resources.flag_jp
import mahjongtournamentsuite.composeapp.generated.resources.flag_ke
import mahjongtournamentsuite.composeapp.generated.resources.flag_kg
import mahjongtournamentsuite.composeapp.generated.resources.flag_kh
import mahjongtournamentsuite.composeapp.generated.resources.flag_ki
import mahjongtournamentsuite.composeapp.generated.resources.flag_km
import mahjongtournamentsuite.composeapp.generated.resources.flag_kn
import mahjongtournamentsuite.composeapp.generated.resources.flag_kp
import mahjongtournamentsuite.composeapp.generated.resources.flag_kr
import mahjongtournamentsuite.composeapp.generated.resources.flag_kw
import mahjongtournamentsuite.composeapp.generated.resources.flag_ky
import mahjongtournamentsuite.composeapp.generated.resources.flag_kz
import mahjongtournamentsuite.composeapp.generated.resources.flag_la
import mahjongtournamentsuite.composeapp.generated.resources.flag_lb
import mahjongtournamentsuite.composeapp.generated.resources.flag_lc
import mahjongtournamentsuite.composeapp.generated.resources.flag_li
import mahjongtournamentsuite.composeapp.generated.resources.flag_lk
import mahjongtournamentsuite.composeapp.generated.resources.flag_lr
import mahjongtournamentsuite.composeapp.generated.resources.flag_ls
import mahjongtournamentsuite.composeapp.generated.resources.flag_lt
import mahjongtournamentsuite.composeapp.generated.resources.flag_lu
import mahjongtournamentsuite.composeapp.generated.resources.flag_lv
import mahjongtournamentsuite.composeapp.generated.resources.flag_ly
import mahjongtournamentsuite.composeapp.generated.resources.flag_ma
import mahjongtournamentsuite.composeapp.generated.resources.flag_mc
import mahjongtournamentsuite.composeapp.generated.resources.flag_md
import mahjongtournamentsuite.composeapp.generated.resources.flag_me
import mahjongtournamentsuite.composeapp.generated.resources.flag_mf
import mahjongtournamentsuite.composeapp.generated.resources.flag_mg
import mahjongtournamentsuite.composeapp.generated.resources.flag_mh
import mahjongtournamentsuite.composeapp.generated.resources.flag_mk
import mahjongtournamentsuite.composeapp.generated.resources.flag_ml
import mahjongtournamentsuite.composeapp.generated.resources.flag_mm
import mahjongtournamentsuite.composeapp.generated.resources.flag_mn
import mahjongtournamentsuite.composeapp.generated.resources.flag_mo
import mahjongtournamentsuite.composeapp.generated.resources.flag_mp
import mahjongtournamentsuite.composeapp.generated.resources.flag_mq
import mahjongtournamentsuite.composeapp.generated.resources.flag_mr
import mahjongtournamentsuite.composeapp.generated.resources.flag_ms
import mahjongtournamentsuite.composeapp.generated.resources.flag_mt
import mahjongtournamentsuite.composeapp.generated.resources.flag_mu
import mahjongtournamentsuite.composeapp.generated.resources.flag_mv
import mahjongtournamentsuite.composeapp.generated.resources.flag_mw
import mahjongtournamentsuite.composeapp.generated.resources.flag_mx
import mahjongtournamentsuite.composeapp.generated.resources.flag_my
import mahjongtournamentsuite.composeapp.generated.resources.flag_mz
import mahjongtournamentsuite.composeapp.generated.resources.flag_na
import mahjongtournamentsuite.composeapp.generated.resources.flag_nc
import mahjongtournamentsuite.composeapp.generated.resources.flag_ne
import mahjongtournamentsuite.composeapp.generated.resources.flag_nf
import mahjongtournamentsuite.composeapp.generated.resources.flag_ng
import mahjongtournamentsuite.composeapp.generated.resources.flag_ni
import mahjongtournamentsuite.composeapp.generated.resources.flag_nl
import mahjongtournamentsuite.composeapp.generated.resources.flag_no
import mahjongtournamentsuite.composeapp.generated.resources.flag_np
import mahjongtournamentsuite.composeapp.generated.resources.flag_nr
import mahjongtournamentsuite.composeapp.generated.resources.flag_nu
import mahjongtournamentsuite.composeapp.generated.resources.flag_nz
import mahjongtournamentsuite.composeapp.generated.resources.flag_om
import mahjongtournamentsuite.composeapp.generated.resources.flag_pa
import mahjongtournamentsuite.composeapp.generated.resources.flag_pe
import mahjongtournamentsuite.composeapp.generated.resources.flag_pf
import mahjongtournamentsuite.composeapp.generated.resources.flag_pg
import mahjongtournamentsuite.composeapp.generated.resources.flag_ph
import mahjongtournamentsuite.composeapp.generated.resources.flag_pk
import mahjongtournamentsuite.composeapp.generated.resources.flag_pl
import mahjongtournamentsuite.composeapp.generated.resources.flag_pm
import mahjongtournamentsuite.composeapp.generated.resources.flag_pn
import mahjongtournamentsuite.composeapp.generated.resources.flag_pr
import mahjongtournamentsuite.composeapp.generated.resources.flag_ps
import mahjongtournamentsuite.composeapp.generated.resources.flag_pt
import mahjongtournamentsuite.composeapp.generated.resources.flag_pw
import mahjongtournamentsuite.composeapp.generated.resources.flag_py
import mahjongtournamentsuite.composeapp.generated.resources.flag_qa
import mahjongtournamentsuite.composeapp.generated.resources.flag_re
import mahjongtournamentsuite.composeapp.generated.resources.flag_ro
import mahjongtournamentsuite.composeapp.generated.resources.flag_rs
import mahjongtournamentsuite.composeapp.generated.resources.flag_ru
import mahjongtournamentsuite.composeapp.generated.resources.flag_rw
import mahjongtournamentsuite.composeapp.generated.resources.flag_sa
import mahjongtournamentsuite.composeapp.generated.resources.flag_sb
import mahjongtournamentsuite.composeapp.generated.resources.flag_sc
import mahjongtournamentsuite.composeapp.generated.resources.flag_sd
import mahjongtournamentsuite.composeapp.generated.resources.flag_se
import mahjongtournamentsuite.composeapp.generated.resources.flag_sg
import mahjongtournamentsuite.composeapp.generated.resources.flag_sh
import mahjongtournamentsuite.composeapp.generated.resources.flag_si
import mahjongtournamentsuite.composeapp.generated.resources.flag_sj
import mahjongtournamentsuite.composeapp.generated.resources.flag_sk
import mahjongtournamentsuite.composeapp.generated.resources.flag_sl
import mahjongtournamentsuite.composeapp.generated.resources.flag_sm
import mahjongtournamentsuite.composeapp.generated.resources.flag_sn
import mahjongtournamentsuite.composeapp.generated.resources.flag_so
import mahjongtournamentsuite.composeapp.generated.resources.flag_sr
import mahjongtournamentsuite.composeapp.generated.resources.flag_ss
import mahjongtournamentsuite.composeapp.generated.resources.flag_st
import mahjongtournamentsuite.composeapp.generated.resources.flag_sv
import mahjongtournamentsuite.composeapp.generated.resources.flag_sx
import mahjongtournamentsuite.composeapp.generated.resources.flag_sy
import mahjongtournamentsuite.composeapp.generated.resources.flag_sz
import mahjongtournamentsuite.composeapp.generated.resources.flag_tc
import mahjongtournamentsuite.composeapp.generated.resources.flag_td
import mahjongtournamentsuite.composeapp.generated.resources.flag_tf
import mahjongtournamentsuite.composeapp.generated.resources.flag_tg
import mahjongtournamentsuite.composeapp.generated.resources.flag_th
import mahjongtournamentsuite.composeapp.generated.resources.flag_tj
import mahjongtournamentsuite.composeapp.generated.resources.flag_tk
import mahjongtournamentsuite.composeapp.generated.resources.flag_tl
import mahjongtournamentsuite.composeapp.generated.resources.flag_tm
import mahjongtournamentsuite.composeapp.generated.resources.flag_tn
import mahjongtournamentsuite.composeapp.generated.resources.flag_to
import mahjongtournamentsuite.composeapp.generated.resources.flag_tr
import mahjongtournamentsuite.composeapp.generated.resources.flag_tt
import mahjongtournamentsuite.composeapp.generated.resources.flag_tv
import mahjongtournamentsuite.composeapp.generated.resources.flag_tw
import mahjongtournamentsuite.composeapp.generated.resources.flag_tz
import mahjongtournamentsuite.composeapp.generated.resources.flag_ua
import mahjongtournamentsuite.composeapp.generated.resources.flag_ug
import mahjongtournamentsuite.composeapp.generated.resources.flag_um
import mahjongtournamentsuite.composeapp.generated.resources.flag_us
import mahjongtournamentsuite.composeapp.generated.resources.flag_uy
import mahjongtournamentsuite.composeapp.generated.resources.flag_uz
import mahjongtournamentsuite.composeapp.generated.resources.flag_va
import mahjongtournamentsuite.composeapp.generated.resources.flag_vc
import mahjongtournamentsuite.composeapp.generated.resources.flag_ve
import mahjongtournamentsuite.composeapp.generated.resources.flag_vg
import mahjongtournamentsuite.composeapp.generated.resources.flag_vi
import mahjongtournamentsuite.composeapp.generated.resources.flag_vn
import mahjongtournamentsuite.composeapp.generated.resources.flag_vu
import mahjongtournamentsuite.composeapp.generated.resources.flag_wf
import mahjongtournamentsuite.composeapp.generated.resources.flag_ws
import mahjongtournamentsuite.composeapp.generated.resources.flag_xk
import mahjongtournamentsuite.composeapp.generated.resources.flag_ye
import mahjongtournamentsuite.composeapp.generated.resources.flag_yt
import mahjongtournamentsuite.composeapp.generated.resources.flag_za
import mahjongtournamentsuite.composeapp.generated.resources.flag_zm
import mahjongtournamentsuite.composeapp.generated.resources.flag_zw

internal fun flagResourceFor(code: String): DrawableResource? = when (code) {
    "AD" -> Res.drawable.flag_ad
    "AE" -> Res.drawable.flag_ae
    "AF" -> Res.drawable.flag_af
    "AG" -> Res.drawable.flag_ag
    "AI" -> Res.drawable.flag_ai
    "AL" -> Res.drawable.flag_al
    "AM" -> Res.drawable.flag_am
    "AO" -> Res.drawable.flag_ao
    "AQ" -> Res.drawable.flag_aq
    "AR" -> Res.drawable.flag_ar
    "AS" -> Res.drawable.flag_as
    "AT" -> Res.drawable.flag_at
    "AU" -> Res.drawable.flag_au
    "AW" -> Res.drawable.flag_aw
    "AX" -> Res.drawable.flag_ax
    "AZ" -> Res.drawable.flag_az
    "BA" -> Res.drawable.flag_ba
    "BB" -> Res.drawable.flag_bb
    "BD" -> Res.drawable.flag_bd
    "BE" -> Res.drawable.flag_be
    "BF" -> Res.drawable.flag_bf
    "BG" -> Res.drawable.flag_bg
    "BH" -> Res.drawable.flag_bh
    "BI" -> Res.drawable.flag_bi
    "BJ" -> Res.drawable.flag_bj
    "BL" -> Res.drawable.flag_bl
    "BM" -> Res.drawable.flag_bm
    "BN" -> Res.drawable.flag_bn
    "BO" -> Res.drawable.flag_bo
    "BQ" -> Res.drawable.flag_bq
    "BR" -> Res.drawable.flag_br
    "BS" -> Res.drawable.flag_bs
    "BT" -> Res.drawable.flag_bt
    "BV" -> Res.drawable.flag_bv
    "BW" -> Res.drawable.flag_bw
    "BY" -> Res.drawable.flag_by
    "BZ" -> Res.drawable.flag_bz
    "CA" -> Res.drawable.flag_ca
    "CC" -> Res.drawable.flag_cc
    "CD" -> Res.drawable.flag_cd
    "CF" -> Res.drawable.flag_cf
    "CG" -> Res.drawable.flag_cg
    "CH" -> Res.drawable.flag_ch
    "CI" -> Res.drawable.flag_ci
    "CK" -> Res.drawable.flag_ck
    "CL" -> Res.drawable.flag_cl
    "CM" -> Res.drawable.flag_cm
    "CN" -> Res.drawable.flag_cn
    "CO" -> Res.drawable.flag_co
    "CR" -> Res.drawable.flag_cr
    "CU" -> Res.drawable.flag_cu
    "CV" -> Res.drawable.flag_cv
    "CW" -> Res.drawable.flag_cw
    "CX" -> Res.drawable.flag_cx
    "CY" -> Res.drawable.flag_cy
    "CZ" -> Res.drawable.flag_cz
    "DE" -> Res.drawable.flag_de
    "DJ" -> Res.drawable.flag_dj
    "DK" -> Res.drawable.flag_dk
    "DM" -> Res.drawable.flag_dm
    "DO" -> Res.drawable.flag_do
    "DZ" -> Res.drawable.flag_dz
    "EC" -> Res.drawable.flag_ec
    "EE" -> Res.drawable.flag_ee
    "EG" -> Res.drawable.flag_eg
    "EH" -> Res.drawable.flag_eh
    "ER" -> Res.drawable.flag_er
    "ES" -> Res.drawable.flag_es
    "ET" -> Res.drawable.flag_et
    "EU" -> Res.drawable.flag_eu
    "FI" -> Res.drawable.flag_fi
    "FJ" -> Res.drawable.flag_fj
    "FK" -> Res.drawable.flag_fk
    "FM" -> Res.drawable.flag_fm
    "FO" -> Res.drawable.flag_fo
    "FR" -> Res.drawable.flag_fr
    "GA" -> Res.drawable.flag_ga
    "GB" -> Res.drawable.flag_gb
    "GD" -> Res.drawable.flag_gd
    "GE" -> Res.drawable.flag_ge
    "GF" -> Res.drawable.flag_gf
    "GG" -> Res.drawable.flag_gg
    "GH" -> Res.drawable.flag_gh
    "GI" -> Res.drawable.flag_gi
    "GL" -> Res.drawable.flag_gl
    "GM" -> Res.drawable.flag_gm
    "GN" -> Res.drawable.flag_gn
    "GP" -> Res.drawable.flag_gp
    "GQ" -> Res.drawable.flag_gq
    "GR" -> Res.drawable.flag_gr
    "GS" -> Res.drawable.flag_gs
    "GT" -> Res.drawable.flag_gt
    "GU" -> Res.drawable.flag_gu
    "GW" -> Res.drawable.flag_gw
    "GY" -> Res.drawable.flag_gy
    "HK" -> Res.drawable.flag_hk
    "HM" -> Res.drawable.flag_hm
    "HN" -> Res.drawable.flag_hn
    "HR" -> Res.drawable.flag_hr
    "HT" -> Res.drawable.flag_ht
    "HU" -> Res.drawable.flag_hu
    "ID" -> Res.drawable.flag_id
    "IE" -> Res.drawable.flag_ie
    "IL" -> Res.drawable.flag_il
    "IM" -> Res.drawable.flag_im
    "IN" -> Res.drawable.flag_in
    "IO" -> Res.drawable.flag_io
    "IQ" -> Res.drawable.flag_iq
    "IR" -> Res.drawable.flag_ir
    "IS" -> Res.drawable.flag_is
    "IT" -> Res.drawable.flag_it
    "JE" -> Res.drawable.flag_je
    "JM" -> Res.drawable.flag_jm
    "JO" -> Res.drawable.flag_jo
    "JP" -> Res.drawable.flag_jp
    "KE" -> Res.drawable.flag_ke
    "KG" -> Res.drawable.flag_kg
    "KH" -> Res.drawable.flag_kh
    "KI" -> Res.drawable.flag_ki
    "KM" -> Res.drawable.flag_km
    "KN" -> Res.drawable.flag_kn
    "KP" -> Res.drawable.flag_kp
    "KR" -> Res.drawable.flag_kr
    "KW" -> Res.drawable.flag_kw
    "KY" -> Res.drawable.flag_ky
    "KZ" -> Res.drawable.flag_kz
    "LA" -> Res.drawable.flag_la
    "LB" -> Res.drawable.flag_lb
    "LC" -> Res.drawable.flag_lc
    "LI" -> Res.drawable.flag_li
    "LK" -> Res.drawable.flag_lk
    "LR" -> Res.drawable.flag_lr
    "LS" -> Res.drawable.flag_ls
    "LT" -> Res.drawable.flag_lt
    "LU" -> Res.drawable.flag_lu
    "LV" -> Res.drawable.flag_lv
    "LY" -> Res.drawable.flag_ly
    "MA" -> Res.drawable.flag_ma
    "MC" -> Res.drawable.flag_mc
    "MD" -> Res.drawable.flag_md
    "ME" -> Res.drawable.flag_me
    "MF" -> Res.drawable.flag_mf
    "MG" -> Res.drawable.flag_mg
    "MH" -> Res.drawable.flag_mh
    "MK" -> Res.drawable.flag_mk
    "ML" -> Res.drawable.flag_ml
    "MM" -> Res.drawable.flag_mm
    "MN" -> Res.drawable.flag_mn
    "MO" -> Res.drawable.flag_mo
    "MP" -> Res.drawable.flag_mp
    "MQ" -> Res.drawable.flag_mq
    "MR" -> Res.drawable.flag_mr
    "MS" -> Res.drawable.flag_ms
    "MT" -> Res.drawable.flag_mt
    "MU" -> Res.drawable.flag_mu
    "MV" -> Res.drawable.flag_mv
    "MW" -> Res.drawable.flag_mw
    "MX" -> Res.drawable.flag_mx
    "MY" -> Res.drawable.flag_my
    "MZ" -> Res.drawable.flag_mz
    "NA" -> Res.drawable.flag_na
    "NC" -> Res.drawable.flag_nc
    "NE" -> Res.drawable.flag_ne
    "NF" -> Res.drawable.flag_nf
    "NG" -> Res.drawable.flag_ng
    "NI" -> Res.drawable.flag_ni
    "NL" -> Res.drawable.flag_nl
    "NO" -> Res.drawable.flag_no
    "NP" -> Res.drawable.flag_np
    "NR" -> Res.drawable.flag_nr
    "NU" -> Res.drawable.flag_nu
    "NZ" -> Res.drawable.flag_nz
    "OM" -> Res.drawable.flag_om
    "PA" -> Res.drawable.flag_pa
    "PE" -> Res.drawable.flag_pe
    "PF" -> Res.drawable.flag_pf
    "PG" -> Res.drawable.flag_pg
    "PH" -> Res.drawable.flag_ph
    "PK" -> Res.drawable.flag_pk
    "PL" -> Res.drawable.flag_pl
    "PM" -> Res.drawable.flag_pm
    "PN" -> Res.drawable.flag_pn
    "PR" -> Res.drawable.flag_pr
    "PS" -> Res.drawable.flag_ps
    "PT" -> Res.drawable.flag_pt
    "PW" -> Res.drawable.flag_pw
    "PY" -> Res.drawable.flag_py
    "QA" -> Res.drawable.flag_qa
    "RE" -> Res.drawable.flag_re
    "RO" -> Res.drawable.flag_ro
    "RS" -> Res.drawable.flag_rs
    "RU" -> Res.drawable.flag_ru
    "RW" -> Res.drawable.flag_rw
    "SA" -> Res.drawable.flag_sa
    "SB" -> Res.drawable.flag_sb
    "SC" -> Res.drawable.flag_sc
    "SD" -> Res.drawable.flag_sd
    "SE" -> Res.drawable.flag_se
    "SG" -> Res.drawable.flag_sg
    "SH" -> Res.drawable.flag_sh
    "SI" -> Res.drawable.flag_si
    "SJ" -> Res.drawable.flag_sj
    "SK" -> Res.drawable.flag_sk
    "SL" -> Res.drawable.flag_sl
    "SM" -> Res.drawable.flag_sm
    "SN" -> Res.drawable.flag_sn
    "SO" -> Res.drawable.flag_so
    "SR" -> Res.drawable.flag_sr
    "SS" -> Res.drawable.flag_ss
    "ST" -> Res.drawable.flag_st
    "SV" -> Res.drawable.flag_sv
    "SX" -> Res.drawable.flag_sx
    "SY" -> Res.drawable.flag_sy
    "SZ" -> Res.drawable.flag_sz
    "TC" -> Res.drawable.flag_tc
    "TD" -> Res.drawable.flag_td
    "TF" -> Res.drawable.flag_tf
    "TG" -> Res.drawable.flag_tg
    "TH" -> Res.drawable.flag_th
    "TJ" -> Res.drawable.flag_tj
    "TK" -> Res.drawable.flag_tk
    "TL" -> Res.drawable.flag_tl
    "TM" -> Res.drawable.flag_tm
    "TN" -> Res.drawable.flag_tn
    "TO" -> Res.drawable.flag_to
    "TR" -> Res.drawable.flag_tr
    "TT" -> Res.drawable.flag_tt
    "TV" -> Res.drawable.flag_tv
    "TW" -> Res.drawable.flag_tw
    "TZ" -> Res.drawable.flag_tz
    "UA" -> Res.drawable.flag_ua
    "UG" -> Res.drawable.flag_ug
    "UM" -> Res.drawable.flag_um
    "US" -> Res.drawable.flag_us
    "UY" -> Res.drawable.flag_uy
    "UZ" -> Res.drawable.flag_uz
    "VA" -> Res.drawable.flag_va
    "VC" -> Res.drawable.flag_vc
    "VE" -> Res.drawable.flag_ve
    "VG" -> Res.drawable.flag_vg
    "VI" -> Res.drawable.flag_vi
    "VN" -> Res.drawable.flag_vn
    "VU" -> Res.drawable.flag_vu
    "WF" -> Res.drawable.flag_wf
    "WS" -> Res.drawable.flag_ws
    "XK" -> Res.drawable.flag_xk
    "YE" -> Res.drawable.flag_ye
    "YT" -> Res.drawable.flag_yt
    "ZA" -> Res.drawable.flag_za
    "ZM" -> Res.drawable.flag_zm
    "ZW" -> Res.drawable.flag_zw
    else -> null
}
